---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapp-deployment
  namespace: apigw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaskapp
  template:
    metadata:
      labels:
        app: flaskapp
    spec:
      containers:
      - name: flaskapp
        image: us-ashburn-1.ocir.io/idcjesmg6idk/flaskapp:3.0
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: ocir-secret

---
apiVersion: v1
kind: Service
metadata:
  name: flaskapp-service
  namespace: apigw
spec:
  selector:
    app: flaskapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer

